version: '3'

services:

  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    volumes:
      - .:/var/www/html